// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// outputs an updated array
RWStructuredBuffer<float3> output;

[numthreads(64, 1 ,1)] // 1 dimension: easier to work with. 64 works on most platforms.
void CSMain (uint3 id : SV_DispatchThreadID) //SV_DISPATCHThreadID uses numThreads
{
    output[id.x] = float3(id.x, 0, 0);
    
    //Result[id.xy] = float4(id.x & id.y, (id.x & 15)/15.0, (id.y & 15)/15.0, 0.0);
}
